version: '3.5'

services:
  mifosx-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:443'
    environment:
      - FINERACT_API_PROVIDER=/fineract-provider/api
      - FINERACT_API_VERSION=/v1
      - FINERACT_PLATFORM_TENANT_IDENTIFIER=default
      - MIFOS_SESSION_IDLE_TIMEOUT=300000
      - MIFOS_OAUTH_SERVER_ENABLED=false
    volumes:
      - /home/elyvium/projects/keycloak/certs:/certs:ro
